project:
  type: website
  output-dir: docs

website:
  title: "Tour de Chao"
  description: "Sharing my travel experiences tout le monde."
  favicon: archie-icon.jpg
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - simplex
      - brand
    css: styles.css



