---
title: "A whirlewind in Galacia and Porto"
date: 2025-08-05
categories: [travel, galicia, porto, wine]
---

My philosophy for many things in life is this: "leave things where you still want more", in other words, "less is more". We tood by it with our recent Galicia - Porto trip. We spent **only** 3 nights 4 days in the Rias Baixas region of Galicia and Porto: 3.5 days and 2 nights in Rais Baixas, 1.5 days and 1 night in Porto. No, we didn't have enough time, and that's great. 

Why Galicia, you might ask? Percebes, aka goose barnacles. If you are my friend, you would know most of my travels are motivated by nose and palette (with a dash of sight).
I first heard of Percebes from a food documentary, more than 10 years ago. I was fascinated by both their apparent inedibility and the challenge of harvesting them. I had attempted to try them during my first trip to Spain in Barcelona, then subsequent trips, but each time I convinced myself to postpone the rendezvous, because I wanted it done right: fresh, cooked by locals, enjoyed on the Galician coast. Of course, Galicia is known for its top quality seafood besides Percebes, with beautiful Albariños to match.

So that's how I went.

## Getting there

Getting to Galicia from Chicago, you have two choices: fly into Santiago de Compostella airport, or Porto airport (of course, you have to connect via MAD or London, etc.) Particularly, we want to visit Rias Baixas, which is about similar distance driving from either airport (about 1.5 hours). Although we later found out that you can fly from MAD to Vigo, which is in Rias Baixas, and only 30 minutes from the hotel.

## Where we stayed

We picked ([Pepe Vieira](https://maps.app.goo.gl/Dq1k397jvPe551Nq6)) ()

## Mangia


## drinka


How did the Percebes taste? To quote Eva Langoria in Searching for Spain: it taste like the ocean! 🙃

